' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/24/20 by tuan
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks


' Open
Set Part = swApp.OpenDoc6("D:\elastic_robot_arm\source\me\elastic_robot_arm\base_bot_2.SLDPRT", 1, 0, "", longstatus, longwarnings)
swApp.ActivateDoc2 "base_bot_2.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("Boss-Extrude2", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cut-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch7", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Cut-Extrude2", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch6", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Boss-Extrude4", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch5", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Boss-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch4", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Boss-Extrude2", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch2", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditSketch
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Arc4", "SKETCHSEGMENT", 0.05131708594008779767, 0.002499999999999972296, -0.003941747180897944847, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc5", "SKETCHSEGMENT", 0.04551602405120772077, 0.002499999999999898571, -0.01450265472219246926, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line10", "SKETCHSEGMENT", 0.0450697885212938687, 0.002499999999999909846, -0.01286645777917500705, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc3", "SKETCHSEGMENT", -0.008478475068368518386, 0.002500000000000032578, 0.004685473064103218288, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc6", "SKETCHSEGMENT", 0.04655724028767335709, 0.002500000000000118447, 0.01703132272505315792, True, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Arc2", "SKETCHSEGMENT", 0.0538457539429329779, 0.002500000000000092426, 0.01331269330910438142, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.02870781909111924657, 0.002500000000000112375, 0.01613885166522545378, False, 0, Nothing, 0)
Part.EditDelete

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Part.EditSketch
Part.ClearSelection2 True
Part.EditUndo2 1
Part.EditUndo2 1
Part.ClearSelection2 True
Part.EditUndo2 1
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.02513793485180840226, 0.002500000000000157045, 0.02253489426065734269, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Arc2", "SKETCHSEGMENT", 0.06068803206827871888, 0.002500000000000020869, 0.003049276121085756075, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMinimized
Part.SketchManager.InsertSketch True

' Open
Set Part = swApp.OpenDoc6("D:\elastic_robot_arm\source\me\elastic_robot_arm\elastic_robot_arm.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
swApp.ActivateDoc2 "elastic_robot_arm.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, -0.06475038293658366695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.08633384391544489389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05497787143782150582, -0.1295007658731673339
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.1007228179013523739
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.09352833090839862695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, -0.06475038293658366695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.07194486992953741389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, -0.08633384391544489389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.08633384391544489389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04466952054322997218, -0.1223062788802136008
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, -0.1223062788802136008
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04466952054322997218, -0.1295007658731673339
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.1223062788802136008
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04466952054322997218, -0.1654732008379360408
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.1366952528661210808
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.07194486992953741389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.08633384391544489389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.05755589594362993389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, -0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.05755589594362993389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, -0.06475038293658366695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.05036140895067618695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05841398840268535037, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0927751580513237889, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06185010536754918797, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.07903069019186842459, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04123340357836613457, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04810563750809381672, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.07559457322700456616, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
boolstatus = Part.Extension.SelectByID2("Joint_1_Cap-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_1_Load_Base-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_1_Load_Gear-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_1_Motor_Gear-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_1_Shaft-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_2_Cap-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_2_Load_Base-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_2_Load_Gear-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft_Cap-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft_bearing_limit-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft_bearing_limit-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_1_Shaft_2-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("CUI_DEVICES_cui_devices_amt203s-0096-6000-s-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_2_Motor_Gear-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("GA25_39RPM-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft_motor_bearing_limit-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("base_top-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("GA25_39RPM-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Joint_1_Motor_Support-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("base_bot-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("CUI_DEVICES_cui_devices_amt203s-0096-6000-s-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("GA25_39RPM-1@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("GA25_39RPM-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.5745992343747131637
Dim swTranslation() As Double
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.1630518821331080614
swTranslation(1) = -0.01457120002746164697
swTranslation(2) = -0.1164155451870465541
Dim swTranslationVar As Variant
swTranslationVar = swTranslation
Dim swMathUtils As Object
Set swMathUtils = swApp.GetMathUtility()
Dim swTranslationVector As MathVector
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.6922882341864015077
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.1811129980765724679
swTranslation(1) = -0.02082539416139892255
swTranslation(2) = -0.1402596929964416705
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Link_2_Shaft_bearing_limit-2@elastic_robot_arm", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.013006166368593863
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.148672777897360997
swTranslation(1) = -0.01923569468284001133
swTranslation(2) = -0.271963214854507862
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.220489357070595027
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.1691283376015029483
swTranslation(1) = -0.03286474004961741774
swTranslation(2) = -0.3276665239210939662
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.47046910490433147
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.1940735656220234917
swTranslation(1) = -0.04928527663609622023
swTranslation(2) = -0.3947789444832457417
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.05755589594362993389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.02877794797181496694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, 0.04316692195772244695, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, 0.03597243496476870694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.03597243496476870694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0.02877794797181496694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.02877794797181496694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.02877794797181496694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0.02877794797181496694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, 0.03597243496476870694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04123340357836613457, 0.05036140895067618695, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.02158346097886122347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, 0.03597243496476870694, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.01438897398590748347, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007194486992953741736, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.04566642611115412365, -0.1553780765926262575, 0.07588474625271146579
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.05755589594362993389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.03597243496476870694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04316692195772244695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02877794797181496694
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.02158346097886122347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007194486992953741736, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01438897398590748347, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03597243496476870694, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02877794797181496694, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.04316692195772244695, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01438897398590748347, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02158346097886122347, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01438897398590748347, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.05557485075223667081, -0.2491182589588731844, -0.01918871488970808059
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007194486992953741736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.08633384391544489389
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.2661960187392884425
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.2158346097886122417
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.2374180707674734547
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.1582787138449822939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.09352833090839862695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.07913935692249114695
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01438897398590748347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.07913935692249114695, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02158346097886122347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.03597243496476870694, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, -0.01438897398590748347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.02158346097886122347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03779728661350228308, -0.01438897398590748347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05497787143782150582, -0.02158346097886122347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.01438897398590748347, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007194486992953741736, 0.02987962268712252012, -0.1911405469273859126, -0.01854362214501747985

' Save
boolstatus = Part.Save3(1, swErrors, swWarnings)
' MSGBOX
' Save changes to base_bot_2.SLDPRT?

Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "base_bot_2.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
